[project_cfg]
name = "OrderBookDex"

[monitor]
pprof_enable = true
pprof_port = 6060

[log]
compress = false
leep_days = 7
level = "info"
mode = "console"
path = "logs/relayer"
service_name = "easyswap-sync"

[db]
database = "easyswap"
password = "123456"
port = 3306
max_open_conns = 1500
host = "127.0.0.1"
log_level = "info"
max_conn_max_lifetime = 300
user = "root"
max_idle_conns = 10

[kv]
[[kv.redis]]
pass = ""
host = "127.0.0.1:6379"
type = "node"

[ankr_cfg]
api_key="4ee932554141e1b1126da400330a2077183007950bcdf7b34078a98e3b253fe3"
https_url="https://rpc.ankr.com/eth_sepolia/"
#https_url="https://rpc.ankr.com/optimism"

[chain_cfg]
name="sepolia"
id=11155111

[contract_cfg]
eth_address = "0x0000000000000000000000000000000000000000"
weth_address = "0x4200000000000000000000000000000000000006"
dex_address = "0x827B2Eb914d2AaB14CA3C735dF0D73A220E59F3F" # undeploy
